### ISSUE TITLE
Enhancement - Dependencies as extras

### ISSUE THREAD

**Issue by bachsh** [drorvinkler/thornfield#1]
Some people would want to install either redis or postgres (or none), so adding both as dependencies can be annoying for deployments (e.g. for psycopg2 you would need to install the postgres dev package on your system).
You might want to not use that as a dependency that gets installed all the time, but rather add it as an extra when installing.

**Comment by drorvinkler** [comment]
Hi, thank you for your comment.
There are actually no dependencies to this package at this moment.
All external libraries (`yasoo`, `redis` and `psycopg2`) are imported only if needed.

**Comment by bachsh** [comment]
Ohh right. I didn't notice that `requirements.txt` was not included in the `setup.py`.
